# -*- coding: utf-8 -*-
"""Untitled38.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uIL0Ve7znkjypwYZYy2y1NZWdVtLSXzg

# **Análisis de evaluaciones agropecuarias municipales Colombia**

Celda 1: Librerías y subir el archivo
"""

import pandas as pd, numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score, silhouette_samples, adjusted_rand_score, pairwise_distances
from sklearn.decomposition import PCA

pd.set_option('display.width', 200)
pd.set_option('display.max_columns', 30)
sns.set_theme(style='whitegrid')

from google.colab import files
subido = files.upload()          # selecciona el CSV del EVA
archivo = list(subido.keys())[0]
print('Archivo cargado:', archivo)

"""Celda 2: Lectura y limpieza"""

eva = pd.read_csv(archivo, thousands='.', decimal=',')

# Renombrar por posición para evitar problemas con tildes y espacios
eva.columns = ['cod_dep','dep','cod_mun','mun','grupo','subgrupo','cultivo','desag',
               'anio','periodo','sembrada','cosechada','prod','rend','ciclo',
               'estado','cod_cultivo','cientifico']
eva['cod_mun'] = eva['cod_mun'].astype(str).str.zfill(5)

print(eva.shape)
print(eva.dtypes)
eva.head()

"""Celda 3: Panorama general"""

print('Municipios:', eva.cod_mun.nunique(), '| Departamentos:', eva.dep.nunique(),
      '| Cultivos:', eva.cultivo.nunique())
print('Valores nulos por columna:'); print(eva.isna().sum()[eva.isna().sum() > 0])

resumen = eva.groupby(['anio', 'ciclo'])[['sembrada', 'cosechada', 'prod']].sum().round(0)
resumen

"""Celda 4: Área sembrada por año y ciclo

"""

pivot = eva.pivot_table(index='anio', columns='ciclo', values='sembrada', aggfunc='sum') / 1e6
pivot.plot(kind='bar', figsize=(8, 4), color=['#2a9d8f', '#e9c46a'])
plt.ylabel('Millones de hectáreas'); plt.title('Área sembrada por año y ciclo')
plt.xticks(rotation=0); plt.show()

"""Celda 5: Cultivos con mayor área (2025)

"""

d25_top = eva[eva.anio == 2025].groupby('cultivo').sembrada.sum().sort_values(ascending=False).head(12)
d25_top.iloc[::-1].plot(kind='barh', figsize=(8, 5), color='#264653')
plt.xlabel('Hectáreas sembradas'); plt.title('Cultivos con mayor área sembrada, 2025'); plt.show()

"""Celda 6: Matriz municipal (2025)"""

d25 = eva[eva.anio == 2025].copy()
mapa_grupo = {'Cereales': 'cereales', 'Frutales': 'frutales',
              'Cultivos tropicales tradicionales': 'tropicales',
              'Raíces y tubérculos': 'raices', 'Hortalizas': 'hortalizas'}
d25['g'] = d25.grupo.map(mapa_grupo).fillna('otros')

info = d25.groupby('cod_mun')[['mun', 'dep']].first()
area = d25.groupby('cod_mun').sembrada.sum()
perm = d25[d25.ciclo == 'Permanente'].groupby('cod_mun').sembrada.sum().reindex(area.index).fillna(0)
comp = d25.pivot_table(index='cod_mun', columns='g', values='sembrada',
                       aggfunc='sum', fill_value=0)

mun = info.copy()
mun['area_total'] = area
mun['n_cultivos'] = d25.groupby('cod_mun').cultivo.nunique()
mun['log_area'] = np.log(area)
mun['pct_perm'] = perm / area
for g in ['cereales', 'frutales', 'tropicales', 'raices', 'hortalizas']:
    mun['pct_' + g] = comp[g] / area

vars_ = ['log_area', 'n_cultivos', 'pct_perm', 'pct_cereales',
         'pct_frutales', 'pct_tropicales', 'pct_raices', 'pct_hortalizas']
X = mun[vars_].copy()
print('Municipios:', len(X))
X.describe().T.round(2)

"""Celda 7: EDA, efecto del logaritmo"""

fig, ax = plt.subplots(1, 2, figsize=(10, 3.5))
ax[0].hist(mun.area_total, bins=50, color='grey');       ax[0].set_title('Área total (ha)')
ax[1].hist(mun.log_area, bins=50, color='steelblue');    ax[1].set_title('Log del área total')
plt.tight_layout(); plt.show()
print('Asimetría área:', round(mun.area_total.skew(), 2), '-> con log:', round(mun.log_area.skew(), 2))

"""Celda 8: EDA, matriz de correlación"""

plt.figure(figsize=(8, 6))
sns.heatmap(X.corr(), annot=True, fmt='.2f', cmap='coolwarm', center=0, vmin=-1, vmax=1)
plt.title('Matriz de correlación'); plt.show()

"""Celda 9: Estandarización"""

Z = StandardScaler().fit_transform(X)
print('Medias ~0:', Z.mean(axis=0).round(2))
print('Desv. ~1:', Z.std(axis=0).round(2))

"""Celda 10: Función de k-medoides (PAM)"""

D = pairwise_distances(Z, metric='manhattan')     # matriz de distancias (n x n)
De = pairwise_distances(Z, metric='euclidean')    # para calcular siluetas de forma comparable

def pam(D, k):
    n = D.shape[0]
    # BUILD
    medoides = [int(D.sum(axis=1).argmin())]
    while len(medoides) < k:
        actual = D[:, medoides].min(axis=1)
        costos = np.minimum(actual[:, None], D).sum(axis=0)
        costos[medoides] = np.inf
        medoides.append(int(costos.argmin()))
    costo = D[:, medoides].min(axis=1).sum()
    # SWAP
    mejora = True
    while mejora:
        mejora = False
        mejor, mejor_costo = None, costo
        for i in range(k):
            otros = medoides[:i] + medoides[i + 1:]
            actual = D[:, otros].min(axis=1)
            costos = np.minimum(actual[:, None], D).sum(axis=0)
            costos[medoides] = np.inf
            h = int(costos.argmin())
            if costos[h] < mejor_costo - 1e-9:
                mejor, mejor_costo = (i, h), costos[h]
        if mejor:
            medoides[mejor[0]] = mejor[1]
            costo = mejor_costo
            mejora = True
    etiquetas = D[:, medoides].argmin(axis=1)
    return np.array(medoides), etiquetas, costo

# Prueba rápida
med, lab, c = pam(D, 4)
print('Tamaños de grupo PAM (k=4):', np.bincount(lab), '| costo:', round(c, 1))

"""Celda 11: Elección del número de grupos"""

ks = range(2, 11)
inercia, sil_km, sil_pam = [], [], []
for k_ in ks:
    km_ = KMeans(n_clusters=k_, n_init=25, random_state=2026).fit(Z)
    inercia.append(km_.inertia_)
    sil_km.append(silhouette_score(De, km_.labels_, metric='precomputed'))
    _, lab_, _ = pam(D, k_)
    sil_pam.append(silhouette_score(De, lab_, metric='precomputed'))

fig, ax = plt.subplots(1, 3, figsize=(14, 3.8))
ax[0].plot(ks, inercia, 'o-');  ax[0].set_title('Codo (k-medias)'); ax[0].set_xlabel('k'); ax[0].set_ylabel('WSS')
ax[1].plot(ks, sil_km, 'o-', color='darkorange');  ax[1].set_title('Silueta (k-medias)'); ax[1].set_xlabel('k')
ax[2].plot(ks, sil_pam, 'o-', color='green');      ax[2].set_title('Silueta (PAM)'); ax[2].set_xlabel('k')
plt.tight_layout(); plt.show()

pd.DataFrame({'k': list(ks), 'silueta_kmedias': np.round(sil_km, 3), 'silueta_pam': np.round(sil_pam, 3)})

"""Celda 12: Definir K"""

K = 4

"""Celda 13: k-medias"""

km = KMeans(n_clusters=K, n_init=50, random_state=2026).fit(Z)
mun['cluster_km'] = km.labels_ + 1
print(mun.cluster_km.value_counts().sort_index())

"""Celda 14: k-medoides (PAM) y medoides"""

med_idx, lab_pam, costo = pam(D, K)
mun['cluster_pam'] = lab_pam + 1
print(mun.cluster_pam.value_counts().sort_index())

print('\nMedoides (municipios representativos):')
medoides = mun.iloc[med_idx][['dep', 'mun', 'area_total', 'n_cultivos', 'pct_perm']].copy()
medoides.insert(0, 'cluster', np.arange(1, K + 1))
medoides.round(2)

"""Celda 15: Comparación de métodos"""

sil_k = silhouette_samples(De, mun.cluster_km.values - 1, metric='precomputed')
sil_p = silhouette_samples(De, mun.cluster_pam.values - 1, metric='precomputed')

tabla = pd.DataFrame({'Método': ['k-medias', 'k-medoides'],
                      'Silueta media': [sil_k.mean(), sil_p.mean()]}).round(3)
print(tabla.to_string(index=False))
print('\nÍndice de Rand ajustado entre ambas particiones:',
      round(adjusted_rand_score(mun.cluster_km, mun.cluster_pam), 3))

cruce = pd.crosstab(mun.cluster_km, mun.cluster_pam, rownames=['k-medias'], colnames=['k-medoides'])
print('\nTabla de correspondencia:'); print(cruce)

plt.figure(figsize=(5, 4))
sns.heatmap(cruce, annot=True, fmt='d', cmap='Blues'); plt.title('k-medias vs k-medoides'); plt.show()

"""Celda 16: Silueta por grupo"""

fig, ax = plt.subplots(1, 2, figsize=(11, 3.8))
for a, s, lab, t in [(ax[0], sil_k, mun.cluster_km, 'Silueta por grupo: k-medias'),
                     (ax[1], sil_p, mun.cluster_pam, 'Silueta por grupo: k-medoides')]:
    y0 = 0
    for c in sorted(lab.unique()):
        v = np.sort(s[lab.values == c])
        a.fill_between(np.arange(y0, y0 + len(v)), 0, v, label=f'Grupo {c}')
        y0 += len(v)
    a.axhline(s.mean(), color='red', ls='--'); a.set_title(t); a.legend()
plt.tight_layout(); plt.show()

"""Celda 17: Perfiles de los grupos"""

perfil = mun.groupby('cluster_km').agg(
    n=('area_total', 'size'),
    area_mediana=('area_total', 'median'),
    n_cultivos=('n_cultivos', 'mean'),
    pct_perm=('pct_perm', 'mean'),
    pct_cereales=('pct_cereales', 'mean'),
    pct_frutales=('pct_frutales', 'mean'),
    pct_tropicales=('pct_tropicales', 'mean'),
    pct_raices=('pct_raices', 'mean'),
    pct_hortalizas=('pct_hortalizas', 'mean')).round(2)
perfil

"""Celda 18: Centros de los grupos (heatmap)"""

centros = pd.DataFrame(km.cluster_centers_, columns=vars_, index=[f'Grupo {i}' for i in range(1, K + 1)])
plt.figure(figsize=(9, 3.8))
sns.heatmap(centros, annot=True, fmt='.2f', cmap='coolwarm', center=0)
plt.title('Centros de los grupos (z-score) - k-medias'); plt.show()

"""Celda 19: Nombres de los grupos"""

# Escribe aquí el nombre de cada grupo según los perfiles anteriores
nombres = {1: 'Grupo 1', 2: 'Grupo 2', 3: 'Grupo 3', 4: 'Grupo 4'}
mun['perfil_km'] = mun.cluster_km.map(nombres)
mun.perfil_km.value_counts()

"""Celda 20: PCA de ambos métodos"""

pca = PCA(n_components=2, random_state=2026)
P = pca.fit_transform(Z)
print('Varianza explicada:', pca.explained_variance_ratio_.round(3), '| total:', pca.explained_variance_ratio_.sum().round(3))

fig, ax = plt.subplots(1, 2, figsize=(12, 4.8))
for a, lab, t in [(ax[0], mun.cluster_km.values, 'k-medias'), (ax[1], mun.cluster_pam.values, 'k-medoides (PAM)')]:
    sns.scatterplot(x=P[:, 0], y=P[:, 1], hue=lab, palette='Set1', s=18, ax=a, legend='full')
    a.set_title(t); a.set_xlabel('PC1'); a.set_ylabel('PC2')
ax[1].scatter(P[med_idx, 0], P[med_idx, 1], marker='X', s=160, c='black', label='medoides')
ax[1].legend()
plt.tight_layout(); plt.show()

"""Celda 21: Grupos por departamento"""

top_dep = mun.dep.value_counts().head(15).index
cruce_dep = pd.crosstab(mun.dep, mun.cluster_km).loc[top_dep]
cruce_dep.plot(kind='barh', stacked=True, figsize=(9, 6), colormap='Set1')
plt.xlabel('Número de municipios'); plt.title('Grupos (k-medias) en los 15 departamentos con más municipios')
plt.gca().invert_yaxis(); plt.show()
cruce_dep

"""Celda 22: Exportar resultados"""

salida = mun.reset_index()[['cod_mun', 'dep', 'mun', 'area_total', 'n_cultivos'] + vars_[2:] + ['cluster_km', 'cluster_pam', 'perfil_km']]
salida.to_csv('eva_municipios_clusters.csv', index=False, encoding='utf-8-sig')
files.download('eva_municipios_clusters.csv')